let str = "karrik";
let str2 = "prajapat";

console.log(str.length);

console.log(str[3]);

// tamplate Literals 

let specialstr = `Hello my name is kartik prajapat`;
console.log(specialstr ,"\n\n\n\n");

console.log()
console.log()

let obj = {
    item: `pen`,
    price: 10,
    name: ` boll`
};

let objstr = `The cost of ${obj.item} is ${obj.price} and brand name is ${obj.name}`;

console.log(objstr);

console.log()
console.log()

console.log("The cost of ", obj.item, "is" , obj.price, "and brand name is ",obj.name ,  `${5+7}`);




